// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACWgRg4qhyw6rX6vkJGsM4qFdGrTaJc1c',
    appId: '1:436881433280:web:424b44340e99ee7232c325',
    messagingSenderId: '436881433280',
    projectId: 'flutter-chat-app-58fe4',
    authDomain: 'flutter-chat-app-58fe4.firebaseapp.com',
    storageBucket: 'flutter-chat-app-58fe4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9bVwAfWE74XlwFGJMc1DiANncFDjo970',
    appId: '1:436881433280:android:49bb8c39a4256ef632c325',
    messagingSenderId: '436881433280',
    projectId: 'flutter-chat-app-58fe4',
    storageBucket: 'flutter-chat-app-58fe4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAN8LjEP1Tg2z-vJpLZTHzRVEr6nhyhqls',
    appId: '1:436881433280:ios:fa8fbc04d7fe0be332c325',
    messagingSenderId: '436881433280',
    projectId: 'flutter-chat-app-58fe4',
    storageBucket: 'flutter-chat-app-58fe4.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );
}
